/*==============================================================*/
/* Table: CODIGO_POSTAL                                         */
/*==============================================================*/
create table CODIGO_POSTAL (
   ID_CODGIGO_POSTAL    VARCHAR(30)           not null,
   DESCRIPCION          VARCHAR(50),
   constraint PK_CODIGO_POSTAL primary key (ID_CODGIGO_POSTAL)
);

INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(910001,Leticia);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(50001,Medellín);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(810001,Arauca);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(80001,Barranquilla);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(110111,Bogotá);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES( 130003,Cartagena de Indias);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(150001,Tunja);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(170001,Manizales);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(180001,Florencia);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(850001,Yopal);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(190001,Popayán);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(200001,Valledupar);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(270001,Quibdó);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(230001,Montería);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(110141,Bogotá);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(940001,Inírida);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(950001,San José del Guaviare);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(410001,Neiva);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(440001,Riohacha);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(470001,Santa Marta);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(500001,Villavicencio);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(520001,Pasto);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(540001,San José de Cúcuta);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(860001,Mocoa);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(630001,Armenia);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(600000,Pereira);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(880001,San Andrés);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(680001,Bucaramanga);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(250251,Sincelejo);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(681012,Ibagué);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(760000,Cali);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(970001,Mitú);
INSERT INTO (ID_CODIGO_POSTAL, DESCRIPCION)VALUES(990001,Puerto Carreño);
